# Generated by Django 4.1.5 on 2023-01-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeafultApp', '0002_maincategories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeHeroBanner',
            new_name='HomeCarousel',
        ),
        migrations.RenameModel(
            old_name='MainCategories',
            new_name='HomeCategories',
        ),
        migrations.RenameField(
            model_name='homecategories',
            old_name='imageurl',
            new_name='imageCategory',
        ),
        migrations.RenameField(
            model_name='homecategories',
            old_name='title',
            new_name='titleCategory',
        ),
    ]
