# Generated by Django 4.1.5 on 2023-01-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeafultApp', '0003_rename_homeherobanner_homecarousel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
