# Generated by Django 4.1.5 on 2023-01-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeafultApp', '0004_featuredproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageurl', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
    ]
