# Generated by Django 4.1.5 on 2023-02-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeafultApp', '0006_shopproducts_delete_shoppingproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='shopproducts',
            old_name='imageurl',
            new_name='imageproduct',
        ),
        migrations.RemoveField(
            model_name='shopproducts',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shopproducts',
            name='ostcategory',
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ShopOstCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostcategoryname', models.CharField(max_length=100)),
                ('categorytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeafultApp.shopcategory')),
            ],
        ),
        migrations.AddField(
            model_name='shopproducts',
            name='ostcategorytype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DeafultApp.shopostcategory'),
        ),
    ]
